version: '3'
services:
  database-images:
    image: mongo:latest
    container_name: database-images
    ports:
      - '27023-27025:27017-27019'
    volumes:
      - database-images-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: gui-database-images
    restart: unless-stopped
    ports:
      - '9091:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: database-images
    depends_on:
      - database-images

  database-security:
    image: mongo:latest
    container_name: database-security
    restart: unless-stopped
    volumes:
      - database-security-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
     - network-security

  security-micro:
    image: damiankaplon/security-micro
    container_name: security-micro
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - database-security
    networks:
      - network-security

volumes:
  database-images-data:
    external: true
  database-security-data:
    external: true

networks:
  network-security:
    external: true
