version: '3'
services:
  database-security:
    image: mongo:latest
    container_name: database-security
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - database-security-data:/data/db
      - ../security-micro/src/main/docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: gui-database-security
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: database-security
    depends_on:
      - database-security

  security-micro:
    image: damiankaplon/security-micro
    container_name: security-micro
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - database-security

volumes:
  database-security-data:
    external: true
