name: Run every modules tests

on:
  push:
    branches: [ "main", "ci/cd-config" ]
  pull_request:
    branches: [ "main", "ci/cd-config" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3.4.0
        with:
          java-version: 17

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.6.3

      - name: Set up and run every modules tests
        run: make run-tests
        